import os
from datetime import datetime
from typing import Dict

class ReportingService:
    def __init__(self, report_dir="reports"):
        self.report_dir = report_dir
        if not os.path.exists(self.report_dir):
            os.makedirs(self.report_dir)

    def generate_student_profile(self, session_data: Dict) -> str:
        """
        Generates a Markdown report for a student session.
        """
        session_id = session_data.get('session_id', 'unknown')
        user_id = session_data.get('user_id', 'Guest')
        domain = session_data.get('domain', 'General')
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # 1. Header
        report = [
            f"# 🎓 Student Knowledge Profile: Session #{session_id[:8]}",
            f"**Student:** {user_id}",
            f"**Date:** {timestamp}",
            f"**Domain:** {domain.upper()}",
            "\n---",
            "\n## 📊 Mastery Heatmap (Bayesian Confidence)",
            "\n| Concept | Mastery Probability $P(L)$ | Status |",
            "| :--- | :--- | :--- |"
        ]

        # 2. Mastery Heatmap
        k_state = session_data.get('knowledge_state')
        if k_state and hasattr(k_state, 'mastery_probs'):
            for concept, prob in k_state.mastery_probs.items():
                status = "⚪ Not Started"
                if prob > 0.8: status = "✅ **Mastered**"
                elif prob > 0.5: status = "✅ Mastered" # Lower threshold for simple view
                elif prob > 0.4: status = "🟡 Learning"
                elif prob > 0.15: status = "🔴 **Critical Gap**"
                
                # Highlight critical rows
                row = f"| {concept.replace('_', ' ').title()} | {prob:.2f} | {status} |"
                if prob > 0.8 or prob < 0.3:
                    row = f"| **{concept.replace('_', ' ').title()}** | **{prob:.2f}** | {status} |"
                
                report.append(row)
        else:
            report.append("| No Data | 0.00 | N/A |")

        # 3. Behavioral Analysis (Mocked logic for now based on session history)
        history = session_data.get('history', [])
        stress_events = 0
        flow_events = 0
        
        for h in history:
            if h.get('time_taken', 0) < 3 and not h.get('is_correct'):
                stress_events += 1 # Rage click?
            elif h.get('is_correct') and 5 < h.get('time_taken', 0) < 30:
                flow_events += 1
                
        dominant_state = "Neutral"
        if stress_events > 2: dominant_state = "Frustrated"
        elif flow_events > len(history) / 2: dominant_state = "Flow"

        report.extend([
            "\n## 🧠 Behavioral Analysis (Signals)",
            f"*   **Dominant State:** `{dominant_state}`",
            f"*   **Stress Events:** {stress_events} detected.",
            f"*   **Flow Events:** {flow_events} detected."
        ])

        # 4. Intervention Plan (Simple Rule Engine)
        report.append("\n## 🛠️ Recommended Intervention")
        interventions = []
        
        # Check specific weaknesses
        if k_state and hasattr(k_state, 'get_mastery'):
            if k_state.get_mastery('recursion') < 0.4:
                interventions.append("1. **Critical:** Unlock 'Visual Recursion' module (scaffolded interactive mode).")
            if k_state.get_mastery('arrays') < 0.5:
                interventions.append("1. **Foundational:** Review Array Basics before proceeding.")
        
        if not interventions:
            interventions.append("1. **Advance:** Student is ready for the next Unit.")
            interventions.append("2. **Challenge:** Assign 'System Design' synthesis problems.")
            
        report.extend(interventions)
        
        report.append("\n---\n*Generated by EduPulse Teacher Analytics Engine*")

        # Write to file
        report_content = "\n".join(report)
        filename = f"student_profile_{session_id[:8]}.md"
        filepath = os.path.join(self.report_dir, filename)
        
        with open(filepath, "w") as f:
            f.write(report_content)
            
        return filepath
